services:
  # Django Backend
  api:
    build:
      context: ./backend
      target: development
    container_name: django_assessment
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=your-development-secret-key
      - DB_NAME=gunchart_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy

  # React Frontend
  app:
    build:
      context: ./frontend
      target: development
    container_name: react_assessment
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://api:8080/api
    depends_on:
      - api

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: postgres_assessment
    environment:
      POSTGRES_DB: gunchart_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: