# Generated by Django 4.2.7 on 2025-09-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_progress_rate_taskcomment_taskattachment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='unique_task_user'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.UniqueConstraint(fields=('predecessor', 'successor'), name='unique_predecessor_successor'),
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
        migrations.AlterModelTable(
            name='taskassignment',
            table='tasks_assignments',
        ),
        migrations.AlterModelTable(
            name='taskattachment',
            table='tasks_attachments',
        ),
        migrations.AlterModelTable(
            name='taskcomment',
            table='tasks_comments',
        ),
        migrations.AlterModelTable(
            name='taskdependency',
            table='tasks_dependency',
        ),
    ]
