# Generated by Django 4.2.7 on 2025-10-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskDependency',
        ),
    ]
